default:
  APPLICATION_URL_INCORP: $APPLICATION_URL/incorporation
  APPLICATION_URL_DBA: $APPLICATION_URL/dba
  TOB_API_URL: http://api:8080
  TOB_APP_URL: http://localhost:8080
  WALLET_SEED_BCREG: bc_registries_dev_00000000000000
