version: '3'
services:

  bcreg-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SETTINGS_PATH: ../bcreg/settings.yaml
      ENVIRONMENT: ${ENVIRONMENT:-default}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      PYTHON_ENV: ${PYTHON_ENV:-development}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_INDY_DID: ${TOB_INDY_DID:-}
      TOB_INDY_SEED: ${TOB_INDY_SEED:-}
      WALLET_SEED_BCREG: ${WALLET_SEED_BCREG:-}
    external_links:
       - tob_tob-api_1:api
    networks:
      - orgbook
    volumes:
      - ../bcreg:/opt/app-root/bcreg
      - bcreg-agent-wallet:/opt/app-root/src/.indy_client/wallet
    ports:
      - 5000:8000

volumes:
  bcreg-agent-wallet:
networks:
  orgbook:
    external:
      name: tob_tob
