server:
  default:
    DEBUG: true
    INDY_GENESIS_PATH: /opt/app-root/.genesis
    TOB_API_URL: http://api:8080
    VERSION: 0.5.8
    # additional variables used in this file
    WALLET_SEED_BCREG: bc_registries_dev_00000000000000

issuers:
  BCREG:
    jurisdiction:
      name: British Columbia
      abbreviation: BC

    name: BC Corporate Registry
    abbreviation: BCReg
    url: "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/bc-registries-online-services"

    wallet_seed: $WALLET_SEED_BCREG
    claim_types:

    - description: Incorporation
      schema:
        name: incorporation.bc_registries
        version: 1.0.0
        attr_names:
        - legal_entity_id
        - corp_num
        - legal_name
        - org_type
        - addressee
        - address_line_1
        - address_line_2
        - city
        - province
        - postal_code
        - country
        - effective_date
        - end_date

logging:
  default:
    version: 1
    disable_existing_loggers: false
    formatters:
      access:
        format: "%(asctime)s %(levelname)s [%(host)s]: %(request)s %(status)d %(message)s"
      simple:
        format: '%(asctime)s %(levelname)s [%(name)s]: %(message)s'
    handlers:
      access:
        class: logging.StreamHandler
        level: DEBUG
        formatter: access
        stream: ext://sys.stdout
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    loggers:
      asyncio:
        level: WARNING
      indy.libindy:
        level: ERROR
        handlers: [console]
        propagate: false
      sanic.access:
        level: INFO
        handlers: [access]
        propagate: false
      sanic.error:
        level: INFO
        handlers: [access]
        propagate: false
      root:
        # sanic root logger
        level: WARNING
        handlers: [console]
        propagate: false
    root:
      level: INFO
      handlers: [console]
